[package]
name = "stun_codec"
version = "0.1.0"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]

[dependencies]
bytecodec = "0.4"
byteorder = "1"
crc = "1"
hmac-sha1 = "0.1"
md5 = "0.3"
trackable = "0.2"
